### ISSUE TITLE
No Overlap Shader Turns Everything White

### ISSUE THREAD

**Issue by Yoshgunn** [Yoshgunn/LightShadowPressRelease#13]
On Level 2-2 I changed the Aqueduct material to a NOverlap shader. Unfortunately, now everything is a stark white. I have no idea why. This is what it looks like when the only light in the scene is a single Point light.

![image](https://cloud.githubusercontent.com/assets/4043081/13438948/4b05e238-dfb9-11e5-943d-abc23a966a35.png)

You can pull the camera around to make the real material appear, but it's inconsistent. It seems almost as if there is a very short range where the material will appear. Like you have to be close up or something. Even then, the rest remain white.

![image](https://cloud.githubusercontent.com/assets/4043081/13439153/450f1326-dfba-11e5-8921-fbd8b101aadf.png)

It's possible I'm misapplying the shader... but I feel like it's the same exact one as Default, which you used in Test2. When I put Default on these objects, the problem still occurs. 

I'll work with the normal shader for now until we figure this out.

**Comment by Jacquies** [comment]
The issue with the overlap lighting was because multiple objects were rendering, using the same grab pass name. Now they won't, although it's a little more expensive now.

We can always revisit this later (because there should be a way to make it work that's less expensive). For now, this solution will work.

Let me know if it's not working.
